image: mcr.microsoft.com/dotnet/core/sdk:2.1

stages:
  - test
  - package

test:
  stage: test
  script:
    - dotnet test

publish_and_package:
  stage: package
  script:
    - wget https://gitlab.com/SealabJaster/AimCLITool/-/jobs/artifacts/v0.0.1.1/raw/linux-x64/aim?job=Bundle -O aim
    - chmod +x ./aim
    - dotnet publish -o ./../bin
    - ./aim deploy pack -d ./bin -a ./.aim/ -v
  artifacts:
    paths:
      - deploy-package.tar
  only:
    - tags