name: .NET Core

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - name: Test with dotnet
      run: dotnet test
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Publish with dotnet
      run: dotnet publish -o ./bin
      
    - name: Create build artifact
      if: startsWith(github.ref, 'v')
      uses: actions/upload-artifact@v1
      with:
        name: dotnet-publish
        path: ./bin/

  package:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'v')
    steps:
      - name: Setup AimCLITool
        run: |
          wget https://gitlab.com/SealabJaster/AimCLITool/-/jobs/artifacts/v0.0.1.1/raw/linux-x64/aim?job=Bundle -O aim
          chmod +x ./aim
      
      - name: Download build artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: dotnet-publish
          path: ./bin/
        
      - name: Package with AimCLITool
        run: ./aim deploy pack -d ./bin -a ./.aim/ -v
        
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifact: ./deploy-package.tar
          token: ${{ secrets.GITHUB_TOKEN }}
