name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
  package:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'v')
    steps:
      - name: Setup AimCLITool
        run: |
          wget https://gitlab.com/SealabJaster/AimCLITool/-/jobs/artifacts/v0.0.1.1/raw/linux-x64/aim?job=Bundle -O aim
          chmod +x ./aim
          
      - name: Publish with .NET Core
        run: dotnet publish -o ./bin
        
      - name: Package with AimCLITool
        run: ./aim deploy pack -d ./bin -a ./.aim/ -v
        
      - name: Upload Package
        uses: actions/upload-artifact@v1
        with:
          name: deployment
          path: deploy-package.tar
